    //类型
app.constant('type',{
        0:'首页banner',
        1:'找职位banner',
        2:'找精英banner',
        3:'行业大图'
    })
    //状态
    .constant('status',{
        1:'草稿',
        2:'上线'
    })
    //上下线
    .constant('down',{
        1:'上线',
        2:'下线'
    })
    //新增，编辑
    .constant('industry',{
        0:'移动互联网',
        1:'电子商务',
        2:'企业服务',
        3:'O2O',
        4:'教育',
        5:'金融',
        6:'游戏'
    })